### ISSUE TITLE
SendEvent Click

### ISSUE THREAD

**Issue by vibou** [Reewr/promise-phantom#14]
Hi everyone,

I am trying to have the click event working on PhantomJS using this library. I draw the rectangle where it is supposed to click to make sure coordinates are correct. When I trigger the click event nothing happened. 

Did you ever try this functionnality ? If so did it work ? 

Here is some sample that can help may be debugging. 

my nodejs code:

`page.sendEvent('click', x, y, 'left').then(function() {
            console.log("--clicked");
            reply(json, response);
          }).catch(cause => {
            console.log("--error: " + cause);
            replyWithError(cause, response);
          });`

I draw using javascript and the computed coordinate a red rectangle and a dot where it is supposed to click as you can see on the snapshot attached.

![newtests-2](https://cloud.githubusercontent.com/assets/1241253/17850252/a28efdd8-685c-11e6-8811-792c4187a78e.png)

finally here are my package.json dependencies:

`"dependencies": {
    "uid-util": "0.0.3",
    "express": "^4.14.0",
    "body-parser": "^1.15.2",
    "fs": "0.0.2",
    "url": "0.11.0",
    "promise-phantom": "3.1.2",
    "optimist": "^0.6.1",
    "util": "0.10.3",
    "eval": "0.1.1",
    "phantomjs-prebuilt": "2.1.7",
    "log-prefix": "0.0.0",
    "promise": "7.1.1",
    "q": "1.4.1"
  }`

I have been working on this quite a while now and I can t get it working. I am not sure if I am doing something wrong or not...

Thank in advance for your help ! :D

**Comment by Reewr** [comment]
Hello! 

I will need to experiment somewhat. Sadly, I don't think I'll have time for that before Thursday as I'm working 12 hour shifts. 

Could you possibly try to do the same by just using PhantomJS? If that works, there may be a bug in either my or the other wrapper being used.

If you know the name, class or id of the button, you could use evaluate, select it and then perform a click through JavaScript. 

Ex:

``` js
page.evaluate(function() {
  document.querySelecter('.class-of-button').click();
}).then(() => {})
```

**Comment by Reewr** [comment]
I have now tested a bit and it seems to work as I expected it to. I tested both with the [element.click()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click) function as well as using the `page.sendEvent()`.

I used [element.getBoundingClientRect()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) to get the position of the element and from there, used the `page.sendEvent` with those coordinates.

I used the following script (just as a test):

``` js
const co = require('co');
const phantomjs = require('promise-phantom');

// Tests whether SendEvent function works.
//
// If working, the following output should be:
//
// 1. Positions of Button { height: 27, left: 10, right: ~98, top: 10, width: ~88 }
// 2. Clicked on body
// 3. Clicked on button
// 4. Clicked on button
//
// 2 and 3 happens because of the `click()` function,
// where as 4 happens due to sendEvent
let generatorFn = function* () {
  let phantom = yield phantomjs.create();
  let page = yield phantom.createPage();
  let html = '<html>' +
    '<head><title>Test</title></head>' +
    '<body style="width: 500px; height: 500px;"><button id="myButton">MyButton</button></body>' +
    '</html>';

  // Add listeners for console and error.
  // Console messages are sent when clicks happens,
  // errors if anything goes wrong
  page.onConsoleMessage(function(message) {
    console.log(message);
  });

  page.onError(function(message) {
    console.log(message);
  });

  yield page.openHtml(html); // then open google

  let position = yield page.evaluate(function() {
    document.body.addEventListener('click', function() {
      console.log('Clicked on body');
    });

    // Retrieve the button we created
    var button = document.getElementById('myButton');

    // Add an event listener to it.
    button.addEventListener('click', function(e) {

      if (e.stopPropagation) {
        e.stopPropagation();
      }

      if (e.preventDefault) {
        e.preventDefault();
      }

      console.log('Clicked on button');
    });

    return button.getBoundingClientRect();
  });

  // Check the button positions
  console.log('Positions of myButton', position);
  // Calculate the positions, clicking in the
  // middle of the button
  let x = position.left + position.width / 2;
  let y = position.top + position.height / 2;

  // Perform clicks with `click` function just to
  // make sure they work.
  yield page.evaluate(function() {
    document.body.click();
    document.getElementById('myButton').click();
  });

  // Send the event, it should work
  yield page.sendEvent('click', x, y, 'left');

  yield page.close();
  yield phantom.exit();
};

// Run the generatorFunction - returns a promise
co(generatorFn);
```

Output of the above script:

```
Positions of myButton { bottom: 37,
  height: 27,
  left: 10,
  right: 98.21875,
  top: 10,
  width: 88.21875 }
Clicked on body
Clicked on button
Clicked on button
```

Please try to retrieve the positions of the button through the use of the evaluate function, as PhantomJS may use different coordinates than yourself.

If you have any more questions or if you have more problems, please let me know.

**Comment by vibou** [comment]
Hi thanks a lot for the tests you provide me. I will try to add some event listener on the button. I did a more simple page and it works. 
I did also a test to click on a DIV within a A and it didn't do anything while clicking on the A directly works. This is a weird behavior but probably due to phantomjs itself and not your library I guess.

I ll let you know after further experimentation on my problematic page :D (which is not a page I made but a website I d like to automate some stuff on it. ;D and I m pretty sure they protect it some what)

**Comment by vibou** [comment]
It seems to actually work. The coordinate I provided was not good. However I couldn't get good coordinate with JS. (because of CSS or anything else)

So as a workaround, I add this style to the button I want to click:

```
position:absolute;
top:0px;
left:0px;
width:0px;
height:0px;
z-index:9999;
```

And then I ask the browser to click at coords: (1,1) :D

**Comment by Reewr** [comment]
I'm glad it worked for you. I would really recommend you to look up information about retrieving correct client position information using JavaScript. 

[Here](http://javascript.info/tutorial/coordinates) a small tutorial that could possibly help you retrieve the coordinates you need. 

This [stackoverflow](http://stackoverflow.com/questions/442404/retrieve-the-position-x-y-of-an-html-element) issue also goes into some details about retrieving the coordinates through JavaScript.

All of the above would need to be done through [page.evaluate](https://github.com/Reewr/promise-phantom/blob/master/docs/webpage.md#Page+evaluate) though, as shown in the test.

**Comment by Reewr** [comment]
@vibou, is it okay to close this issue?

**Comment by vibou** [comment]
Sure ! Thanks again for your help. This lib is the most complete one to make use of phantomJS through NodeJS thanks a lot !
