### ISSUE TITLE
Regex to filter out resource urls from loading

### ISSUE THREAD

**Issue by alexblack** [Reewr/promise-phantom#18]
```
* *Developer Note*: Currently, the networkRequest object does not contain any functions.
   * This is due to an implementation issue in node-phantom-simple. An issue
   * has been created regarding [this]{@link https://github.com/baudehlo/node-phantom-simple/issues/98}
 ```

Since the `networkRequest` object in `onResourceRequested` cannot be implemented, is there another way by which we could prevent urls from being loaded?

I'd propose a list of regexes, passed on startup, that promise-phantom could use to filter urls from being loaded.

**Comment by Reewr** [comment]
The main issue is that promise-phantom is running within nodejs whereas this issue has to be solved within the PhantomJS instance itself, something that node-phantom-simple is responsible for. 

Unless node-phantom-simple supplies such a method, which I don't think it does, I'm afraid I won't be able to do much as by the time I'm sending anything through node-phantom-simple it's already too late. 

The additional problem is that node-phantom-simple has not seen some active development in some time, so adding this implementation most likely won't be trivial either. 

Sorry for the somewhat late reply, I'm still working on my master's and I'll probably be able to take a closer look at this after I'm done with my presentation tomorrow.

**Comment by alexblack** [comment]
Hi, ok thanks for explaining, that makes sense.  

PhantomJS does have a callback for this: http://phantomjs.org/api/webpage/handler/on-resource-requested.html

I wonder one would use it from outside.. what about injecting javascript into the browser?

**Comment by Reewr** [comment]
I managed to think of a solution that may solve your problem. It has been a while since I've worked on this project, but what I said earlier was somewhat incorrect.

node-phantom-simple does have a solution for this exact problem. The main downsides it that the function you're using cannot use variables outside of its scope and has to purely use variables inside the function scope or argument list.

I have not tested whether or not this works yet, but I'm hoping that this example will give you an idea of how to do it.

*Co-based solution*
```js
'use strict';
let co      = require('co');
let driver  = require('promise-phantom');
let options = {path: 'path/to/phantomjs/if/not/in/global/path'};

let renderExample = function* () {
  // Start phantom and create page
  let phantom = yield driver.create(options);
  let page    = yield phantom.createPage();

  // Lets assume that you want to connect to example.com, but filter away
  // all .css resources (just as a simple example)
  // This can be done by using the `setFn` function on the page object
  yield page.setFn('onResourceRequested', function(requestData, networkRequest) {
    // This function wont be able to access any other scope than its own, so no 
    // access to page or phantom etc.
    if (requestData.url.match(/.css/g))
      networkRequest.abort();
  });

  yield page.open('http://www.example.com');
  yield page.set('viewportSize', {width: 640, height: 480});

  // page.renderPdf is exclusive to this wrapper and returns a buffer.
  // For saving to file, use page.render(filename);
  let buffer = yield page.renderPdf();

  return buffer;
};
```
*Promise-based solution*
```js
"use strict";
let driver = require('promise-phantom');
let options = {path: 'path/to/phantomjs/if/not/in/global/path'};
// Promise syntax
driver.create(options)
  .then((phantom) => phantom.createPage())
  .then((page) => {
    // Lets assume that you want to connect to example.com, but filter away
    // all .css resources (just as a simple example)
    // This can be done by using the `setFn` function on the page object
    return page.setFn('onResourceRequested', function(requestData, networkRequest) {
      // This function wont be able to access any other scope than its own, so no 
      // access to page or phantom etc.
      if (requestData.url.match(/.css/g))
        networkRequest.abort();

    }).then(() => page.open('http://www.example.com'))
      .then((status) => page.set('viewportSize', {width: 640, height: 480}))
      .then(() => page.renderPdf())
      .then((buffer) => doSomethingWithPdf(buffer));
  }).catch(console.error.bind(console));
```

This solution will abort all requests that include '.css' within the url itself. If you have multiple regexes, you can check if they all or one match just by adding them into that function. Keep in mind that this function has to use `ES5` syntax as it is executed within the PhantomJS process itself (which uses a seperate JavaScript engine than that of NodeJS). 

I hope that this solution can solve your problem. If it does not or something is unclear, please reply and we'll try to find a way.

**Comment by alexblack** [comment]
Great stuff, thanks for looking into that, yes I can see how that could
work, and I totally get the limitation you're talking about, same thing
that happens when using evaluate to run JS code in phantomjs to inspect the
dom etc.

**Comment by Reewr** [comment]
Were you able check whether or not this method works? If so, is it okay to close this issue?

**Comment by Reewr** [comment]
Closing issue as this is an issue that has been fixed with previous comment. If there's anything else you need help with, feel free to comment and reopen it or create a new one.
