### ISSUE TITLE
page.evaluate function - raised errors aren't caught

### ISSUE THREAD

**Issue by jwarykowski** [Reewr/promise-phantom#7]
Hey @Reewr, I've been using this project recently and I've found that if an error is raised within the page.evaluate function the error isn't caught with the promise catch function e.g

``` js
return page.evaluate(function render() {
      throw new Error('There was an issue rendering!');
    })
    .then((result) => {
        console.log(result); // null
    })
    .catch(function(error) {
        console.log(error); // isn't caught here...
    });
```

Are you aware of this issue? Is there anyway to catch any errors inside the evaluate function?

**Comment by Reewr** [comment]
After checking in PhantomJS, it seems that errors are not in fact caught in the evaluation function. You should still be able to catch them them through using the `page.onError` function, which I have completely failed to make a function for. 

What the `page.evaluate`.catch function is suppose to catch is errors sent by `node-phantom-simple` that has to do with contacting PhantomJS.

Thanks for letting me know about it. I'll update the documentation on this function to mention this.

Below are the comments I'll add when I get home

```
**Developer Note**: Errors that are thrown by this function, through either `throw new Error()`
or other methods, will not be caught by the evaluation function. These are instead caught by
the `page.onError` handler.
```

**Comment by jwarykowski** [comment]
Hey @Reewr, thanks for the quick response. The comment looks good. For the benefit of others, the best way around this is too simple do something like this: 

``` js
return new Promise((resolve, reject) { 
  // the onError function hasn't been added but will be so use below for now
  page._setHandler('onError', (msg, trace) => {
    reject(new Error(`New Error! ${msg}`));
  }); 

  return page.evaluate(function render() {
     // manipulate whatever here, something could throw error
  }).then((value) resolve(value));
});
```

If there is an easier way please let me know 👍

**Comment by Reewr** [comment]
Reopening for visibility - closing once new version is released on NPM.

**Comment by Reewr** [comment]
3.1.2 is now on NPM. Closing issue as fixed.
