### ISSUE TITLE
page.onError function isn't defined

### ISSUE THREAD

**Issue by jwarykowski** [Reewr/promise-phantom#8]
Hey @Reewr, we appear to be missing the `onError` function from the [Web Page Module](http://phantomjs.org/api/webpage/handler/on-error.html). Can I raise a PR adding this in?

To get round this locally, I've simply called `._setHandler` directly e.g.

``` js
page._setHandler('onError', (message, trace) => {
  throw new Error(`Error with message: ${message}`);
});
```

**Comment by Reewr** [comment]
This is just a massive blunder by me. The function should've, of course, been defined together with all of the other handlers. 

No need for a PR unless you want to, though. Requires some docs and testing and I have quite a few commits that rearranges the whole testing of this library laying on my home computer.

Thanks for letting me know!

**Comment by jwarykowski** [comment]
Raised PR #9

**Comment by Reewr** [comment]
Thanks for the PR. It's now merged. Just doing some additional changes before I'm releasing it on NPM.

**Comment by Reewr** [comment]
3.1.2 is now on NPM. Closing issue as fixed.
